# Include the QtPyVCP default menubar.
{% include "default_menubar.yml" %}

qtdesigner:
  ui_file: ( windows.mainwindow.kwargs.ui_file )
  qss_file: ( application.kwargs.stylesheet )

vcp:
  name: MonoKrom Plasma
  version: v0.0.1
  author: Kurt Jacobson
  description: >
    Put a short description of your VCP here. This will be
    shown in the VCP Chooser when launching QtPyVCP with the
    --chooser option.


    Examples of what to included here:
      * VCP Features
      * Type of machine the VCP is for
      * Development status
      * Acknowledgments

data_plugins:
  status:
    kwargs:
      cycle_time: 50

windows:

  mainwindow:
    # Specify the class to use for the VCP's mainwindow
    #   Format: package.module:class
    provider: monokrom.plasma.mainwindow:MainWindow

    # Keyword arguments to pass when initializing the class.
    kwargs:
      # Specify the mainwindow menubar as the default.
      menu: ( default_menubar )
      # Specify the UI file to load the window layout from.
      ui_file: {{ file.dir }}/mainwindow.ui
      # Specify a stylesheet to use only for mainwindow.
      stylesheet: {{ file.dir }}/plasma.qss
      # Set the window title from from the date in the vcp section above.
      title: ( vcp.name ) ( vcp.version)

dialogs:
  open_file:
    provider: monokrom.common.widgets.input_overlay:MkInputOverlay
    kwargs:
      ui_file: {{ file.dir}}/../common/widgets/file_chooser.ui

  recent_files:
    provider: monokrom.common.widgets.input_overlay:MkInputOverlay
    kwargs:
      ui_file: {{ file.dir}}/../common/widgets/recent_file_chooser.ui

application:
  kwargs:
    # Specify the application wide stylesheet.
    stylesheet: {{ file.dir }}/../common/monokrom.qss
    custom_fonts: {{ file.dir }}/../common/fonts/ttf
